agent_name: lst_agent
author: lstolas
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.55.0, <2.0.0'
fingerprint:
  logger_setup.py: bafybeicboqnvizlhdsnmlncvayrswskbyw6vshi34bnrs75qshbz3wdlqu
  no-queue-logging.yaml: bafybeib6k2usocdkxtz6nqa2igxbwkp7f72inrsxtufyy3pttpbojxysay
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeihdawt3eoipfhkdwx2d4hf2lwzznwsysc7t66zcuqn45ifdi5sf54
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeiaz5auftwxpt4czrmeeesggqlkc2kosmetq6adrebeu6g7bkhqc2u
- eightballer/http_server:0.1.0:bafybeidrvllrr23mc6bvjxn6v3hny6oiwhfgi72n2b7w6ck5luousjfbbq
- eightballer/prometheus:0.1.1:bafybeicy4ck2wvauo2vh6ji64xrzlgezh27powi6ztokr4yujtf3cft6wi
- eightballer/apprise_wrapper:0.1.0:bafybeibekoqsadyztskr353x3usoxe4bmjlr45ecafmyfbxay6dc4jxcci
contracts: []
protocols:
- eightballer/default:0.1.0:bafybeicsdb3bue2xoopc6lue7njtyt22nehrnkevmkuk2i6ac65w722vwy
- eightballer/http:0.1.0:bafybeid75xhq7hfdt7sgj7yrn44yj57xrgxscaw34ir46tndfzvodioxme
- eightballer/prometheus:1.0.0:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
- eightballer/user_interaction:0.1.0:bafybeidmfy3vdnlbz6wexi4gwhofown4a7l6jt7nzh2x7lvghumxlgh4vi
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
skills:
- eightballer/prometheus:0.1.0:bafybeicl5i7e467aowfarke4bbyixo2dggar276njmvyuwbsby5pxshhtu
- lstolas/lst_skill:0.1.0:bafybeien4u7b2vme6upapnqnwnzj4vzuqy45axwde6smlddyj5z7bs5qpq
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  handlers:
    queue:
      class: logger_setup.QueuedHandler
      queue_size: 10000
      handler_names:
      - console
      - logfile
      handler_configs:
        console:
          class: logger_setup.BufferedHandler
          formatter: standard
          level: INFO
        logfile:
          class: logging.handlers.TimedRotatingFileHandler
          filename: log.jsonl
          formatter: json
          level: INFO
          when: D
          interval: 1
          backupCount: 7
      formatter_configs:
        standard:
          class: logger_setup.ShortNameFormatter
          format: '[%(levelname)s] %(asctime)s: %(message)s'
          datefmt: '%Y-%m-%dT%H:%M:%S'
        detailed:
          format: '[%(levelname)s|%(pathname)s|L%(lineno)d] %(asctime)s: %(message)s'
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
        json:
          class: logger_setup.JSONFormatter
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
  loggers:
    aea:
      handlers:
      - queue
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
period: 1.0
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: lstolas/lst_abci_app:0.1.0
---
public_id: eightballer/apprise_wrapper:0.1.0
type: connection
config:
  endpoints:
  - ${APPRISE_ENDPOINT:str:null}
